### PR TITLE
Added spec for main module matchers and helpers

### PR DESCRIPTION
**Pull request by petems**
Was writing some specs for the main matchers and stuff and thinking over the layout of the specs and what to do, and now that @jgraichen's stuff has added some specs, I thought I might as well add it now :+1: 

So, I'll probably change the formatting to match up with the existing specs, move the recipe in-line into the spec file etc.

Anyone got any major bugbears? @jgraichen @relistan @technicalpickles?

Thanks :smiley_cat:

### CODE REVIEW

**Comment by jgraichen** [comment]
I don't seen any problems. We may need to restructure the specs if we start to split the `capistrano/spec.rb` in separate modules. But that's another case.

:+1:

**Comment by technicalpickles** [comment]
Looks good to me :+1:

**Comment by technicalpickles** [comment]
Also, let me know if I should enable [Travis-CI](https://travis-ci.org/) for this repo.

**Comment by petems** [comment]
Merged and bumped up, adding to Travis would be great, shall we go for 1.8.7, 1.9.3 and 2.0.0 for versions?

**Comment by technicalpickles** [comment]
@petems yeah, that should be good. 1.8.7 EOLs at some but we may as well keep it around as it's not too difficult to keep support for.

**Comment by petems** [comment]
Cool, I've tested it on my fork on Travis and it always fails with this:

```
/home/travis/build/petems/capistrano-spec/spec/capistrano-spec_spec.rb:4:in `require_relative': cannot load such file --
/home/travis/build/petems/capistrano-spec/spec/recipe/FakeRecipe (LoadError)
```

So I guess I better fix that :+1:

**Pull request merged**
