### PR TITLE
Fix for deprecation message

### PR DESCRIPTION
**Pull request by petems**
Just a quick-one to fix: Spec::Runner.configure -> RSpec.configure

### CODE REVIEW

**Comment by technicalpickles** [comment]
Thanks for contributing! I've added you as a contributor, so you can merge yourself now. If you can send me your rubygems.org email, I can add you as an owner for releasing.

**Comment by petems** [comment]
Awesome, thanks! Will send now :email:

**Comment by relistan** [comment]
Good fix.  I went ahead and merged this and pushed the update gem to Rubygems.  I added "petems" to the authors list in the gem. @petems: if you prefer something else, feel free to change it and republish.

**Comment by petems** [comment]
Cool, I tweaked it a bit. I assume you don't bump the version number up for small change like that?

**Comment by technicalpickles** [comment]
If you want folks to be able to get the release, you would :) Or, you can hold off bumping til you get other changes. I found it better to release early and often, rather than wait for enough changes to 'warrant' a version bump. Versions are cheap, after all.

Since it's a rspec related change, maybe do a minor version bump?

**Comment by relistan** [comment]
I had pushed that change to Rubygems. But if you want your name in the gem to be right then you'd just bump and republish.  I have been tagging the released SHAs with the same tagging scheme that Josh used.

**Comment by petems** [comment]
Ah ok. Yeah, the rspec fix is in the latest release, but I can't deploy til I'm added to the rubygems thingy. My account is here btw :) https://rubygems.org/profiles/petems

**Comment by technicalpickles** [comment]
@petems done!

**Pull request merged**
