### PR TITLE
add support for run_locally

### PR DESCRIPTION
**Pull request by dbyron0**

### CODE REVIEW

**Comment by jhbabon** [comment]
Looks good to me :+1:

BTW, we should review why the Travis build fails. Something related to the version of `rake`.

**Comment by petems** [comment]
Yeah, looks good to me :+1: 

For the travis fail, looks like a 1.8.7 thing?

**Comment by technicalpickles** [comment]
@petems it's 1.8.7 that's failing, but it's failing because:

```
$ bundle exec rake
Could not find rake-0.9.2.2 in any of the sources
Run `bundle install` to install missing gems.
```

Pretty odd that this would fail randomly like this.

**Comment by technicalpickles** [comment]
I thought it might be something intermittent, but a retry of the job failed too. Out of curiousity, I retried master's last build, which succeeded on 1.8.7, and now it's failing with the same error. I'll file something with Travis CI.

**Comment by technicalpickles** [comment]
CI should be fixed now :sparkles:

**Comment by jhbabon** [comment]
@technicalpickles great! Then we could merge. This is a good addition to the library.

**Comment by petems** [comment]
I just re-ran the master build after Travis fixed the Rake issue, so that's green now, let's merge this sucker! :+1:

**Comment by dbyron0** [comment]
Thanks.

**Comment by technicalpickles** [comment]
One comment I originally had is that there aren't any updated docs to go with this change. Then I realized the README is more oriented around how to organize & start testing, rather than being comprehensive on what's available for testing.

Might be a good followup PR for anyone looking to do some doc hacking :grin:

**Pull request merged**
